export const projectsData = [
 {
  "id": "HomeFinder",
  "title": "HomeFinder",
  "subtitle": "Modern Full Stack Real Estate Platform",
  "desc": "HomeFinder is a modern full stack real estate platform where users can discover, buy, rent, and manage properties with a clean, responsive interface. The application features verified property listings, secure authentication, favorites, dashboards, blogs, and seamless communication with property agents.",
  "tags": [
    "Next.js 16",    
    "TypeScript",
    "Node.js",
    "Express.js",
    "MongoDB",    
    "Better Auth",   
    "HeroUI"
  ],
  "image": "/homefinder.png", 
  "featuredBooks": [
    "/homefinder-home.png",
    "/homefinder-explore.png",
    "/homefinder-dashboard.png",
    "/homefinder-property.png"
  ],
  "liveUrl": "https://home-filder.vercel.app",
  "githubUrl": "https://github.com/MDSOBUJMADBOR/HomeFilder",
  "serverGithubUrl": "https://github.com/MDSOBUJMADBOR/HomeFilder-Server",
  "features": [
    "Responsive modern homepage",
    "Browse and search properties",
    "Property details page",
    "Filter by category and location",
    "Sorting options",
    "Featured properties section",
    "About, Blog and Contact pages",
    "Secure Better Auth authentication",
    "Protected dashboard routes",
    "Add and manage properties",
    "Favorites system",
    "Property reviews",
    "Dashboard analytics with charts",
    "Agent contact and live chat UI",
    "Responsive design for all devices"
  ],
  "challenges": [
    "Implementing secure authentication using Better Auth.",
    "Managing property listings and user-specific dashboards.",
    "Building dynamic filtering, searching, and sorting functionality.",
    "Designing a responsive real estate UI with multiple reusable components.",
    "Creating analytics dashboards using Recharts.",
    "Connecting Next.js frontend with Express.js and MongoDB backend."
  ],
  "improvements": [
    "Integrate online payment system.",
    "Add property booking functionality.",
    "Integrate Google Maps for property locations.",
    "Implement advanced search filters.",
    "Add property comparison feature.",
    "Enable real-time notifications.",
    "Support dark mode.",
    "Develop an admin dashboard with approval system.",
    "Implement image upload and optimization.",
    "Add ratings and reviews for properties."
  ]
},
  {
  "id": "SmartAIHub",
  "title": "SmartAI Hub",
  "subtitle": "Modern Full Stack AI Tools Discovery Platform",
  "desc": "SmartAI Hub is a modern full stack AI tools discovery platform where users can explore popular AI tools, search and filter by location, view detailed information, and manage their own AI tool listings through a personalized dashboard. The application includes secure authentication, analytics, AI assistant support, and a clean responsive interface built with Next.js and the MERN Stack.",
  "tags": [
    "Next.js 16",    
    "TypeScript",
    "Node.js",
    "Express.js",
    "MongoDB",   
    "Better Auth",  
    "HeroUI",
    "Recharts"
  ],
  "image": "/smart-ai-hub.png",
  "featuredBooks": [
    "/smart-ai-home.png",
    "/smart-ai-explore.png",
    "/smart-ai-dashboard.png",
    "/smart-ai-assistant.png"
  ],
  "liveUrl": "https://ai-project-client-nine.vercel.app",
  "githubUrl": "https://github.com/MDSOBUJMADBOR/Smart-AI-Hub",
  "serverGithubUrl": "https://github.com/MDSOBUJMADBOR/AI-Project-Server",
  "features": [
    "Responsive modern landing page",
    "Explore popular AI tools",
    "Search AI tools",
    "Filter by location",
    "Sort AI tools",
    "AI tool details page",
    "Featured AI section",
    "Email & Password authentication",
    "Google authentication",
    "GitHub authentication",
    "Better Auth secure authentication",
    "Protected dashboard routes",
    "Dashboard analytics",
    "Add new AI tool",
    "Update AI tool",
    "Delete AI tool",
    "Personal AI listings",
    "Interactive AI Assistant chat",
    "Testimonials section",
    "FAQ section",
    "Newsletter subscription",
    "Responsive design for all devices",
    "Toast notifications",
    "Loading states"
  ],
  "challenges": [
    "Implementing secure authentication with Better Auth.",
    "Building CRUD operations for AI tools using Express.js and MongoDB.",
    "Managing protected dashboard routes and user-specific data.",
    "Developing advanced search, filtering, and sorting functionality.",
    "Creating responsive UI components with HeroUI and Tailwind CSS.",
    "Integrating dashboard analytics using Recharts.",
    "Connecting the Next.js frontend with a RESTful Express API."
  ],
  "improvements": [
    "Add AI categories for easier browsing.",
    "Implement favorites and bookmarks.",
    "Support dark mode.",
    "Introduce AI reviews and ratings.",
    "Build a complete admin dashboard.",
    "Integrate payment gateway for premium AI tools.",
    "Provide personalized AI recommendations.",
    "Improve pagination and lazy loading.",
    "Enhance the AI Assistant with context-aware responses.",
    "Add image upload support for AI tool listings."
  ]
},
{
  "id": "BiblioDrop",
  "title": "BiblioDrop",
  "subtitle": "Modern Full Stack Online Book Delivery Management System",
  "desc": "BiblioDrop is a modern full stack online book delivery management platform that connects readers with local libraries and independent book owners. Users can browse books, request doorstep delivery, make secure Stripe payments, track delivery history, and manage their reading lists, while librarians and administrators efficiently manage books, deliveries, users, and platform analytics.",
  "tags": [
    "Next.js 16",
    "React 19",
    "TypeScript",
    "Node.js",
    "Express.js",   
    "Better Auth",
    "JWT",
    "Stripe",
    "Tailwind CSS v4",
    "HeroUI",
    "Framer Motion",
    "GSAP",
    "Recharts"
  ],
  "image": "/bibliodrop.png",
  "featuredBooks": [
    "/bibliodrop-home.png",
    "/bibliodrop-browse.png",
    "/bibliodrop-details.png",
    "/bibliodrop-admin-dashboard.png"
  ],
  "liveUrl": "https://biblio-drop-client-eosin.vercel.app",
  "githubUrl": "https://github.com/MDSOBUJMADBOR/BiblioDrop-Client",
  "serverGithubUrl": "https://github.com/MDSOBUJMADBOR/BiblioDrop-Server",
  "features": [
    "Modern responsive homepage",
    "Browse published books",
    "Search books by title or author",
    "Filter books by category",
    "Book details page",
    "Doorstep book delivery request",
    "Stripe secure payment integration",
    "Payment success page",
    "Delivery history tracking",
    "Reading list management",
    "Wishlist management",
    "Book review and rating system",
    "Better Auth authentication",
    "Google authentication",
    "JWT authorization",
    "Protected routes",
    "Role-based access control",
    "Persistent user sessions",
    "Librarian dashboard",
    "Add new books",
    "Book cover image upload",
    "Inventory management",
    "Delivery request management",
    "Update delivery status",
    "Admin dashboard",
    "Manage users",
    "Manage books",
    "Manage transactions",
    "Platform analytics",
    "Server-side pagination",
    "Responsive dashboard",
    "Framer Motion animations",
    "GSAP page animations",
    "Toast notifications",
    "Skeleton loading states"
  ],
  "challenges": [
    "Implementing secure authentication and role-based authorization using Better Auth and JWT.",
    "Integrating Stripe payment gateway for secure online delivery fee payments.",
    "Managing multiple dashboards for users, librarians, and administrators.",
    "Building advanced search, category filtering, pagination, and delivery management.",
    "Uploading and managing book cover images using ImgBB API.",
    "Creating responsive and animated UI using Framer Motion and GSAP.",
    "Connecting Next.js frontend with Express.js REST APIs and MongoDB Atlas."
  ],
  "improvements": [
    "Add email verification for new users.",
    "Implement push notifications.",
    "Enable real-time delivery tracking.",
    "Introduce live chat between readers and librarians.",
    "Provide PDF book preview before requesting delivery.",
    "Integrate AI-powered book recommendation system.",
    "Support dark mode.",
    "Add multi-language support.",
    "Implement advanced analytics for librarians.",
    "Develop a mobile application for Android and iOS."
  ]
}
];
